[2022-03-14 19:23:14,862] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: parallel_dag.processing_tasks scheduled__2022-03-11T00:00:00+00:00 [queued]>
[2022-03-14 19:23:15,062] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: parallel_dag.processing_tasks scheduled__2022-03-11T00:00:00+00:00 [queued]>
[2022-03-14 19:23:15,111] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 19:23:15,115] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-03-14 19:23:15,123] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 19:23:15,279] {taskinstance.py:1259} INFO - Executing <Task(SubDagOperator): processing_tasks> on 2022-03-11 00:00:00+00:00
[2022-03-14 19:23:15,404] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'processing_tasks', 'scheduled__2022-03-11T00:00:00+00:00', '--job-id', '108', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dags.py', '--cfg-path', '/tmp/tmpjm9k5hm_', '--error-file', '/tmp/tmpbwvsahx7']
[2022-03-14 19:23:15,461] {standard_task_runner.py:77} INFO - Job 108: Subtask processing_tasks
[2022-03-14 19:23:15,281] {standard_task_runner.py:52} INFO - Started process 3214 to run task
[2022-03-14 19:23:18,632] {logging_mixin.py:109} INFO - Running <TaskInstance: parallel_dag.processing_tasks scheduled__2022-03-11T00:00:00+00:00 [running]> on host airflowvm
[2022-03-14 19:23:22,869] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=processing_tasks
AIRFLOW_CTX_EXECUTION_DATE=2022-03-11T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-11T00:00:00+00:00
[2022-03-14 19:23:23,008] {logging_mixin.py:109} WARNING - /home/airflow/sandbox/lib/python3.8/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-03-14 19:23:23,753] {subdag.py:176} INFO - Created DagRun: scheduled__2022-03-11T00:00:00+00:00
[2022-03-14 19:24:24,118] {base.py:249} INFO - Success criteria met. Exiting.
[2022-03-14 19:24:24,177] {subdag.py:191} INFO - Execution finished. State is success
[2022-03-14 19:24:24,327] {taskinstance.py:1267} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=processing_tasks, execution_date=20220311T000000, start_date=20220314T192314, end_date=20220314T192424
[2022-03-14 19:24:24,449] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-14 19:24:25,225] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
