[2021-12-30 20:59:00,896] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_avaiable 2021-12-29T00:00:00+00:00 [queued]>
[2021-12-30 20:59:00,923] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_avaiable 2021-12-29T00:00:00+00:00 [queued]>
[2021-12-30 20:59:00,924] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-12-30 20:59:00,924] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-12-30 20:59:00,924] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-12-30 20:59:00,939] {taskinstance.py:1087} INFO - Executing <Task(HttpSensor): is_api_avaiable> on 2021-12-29T00:00:00+00:00
[2021-12-30 20:59:00,942] {standard_task_runner.py:52} INFO - Started process 6776 to run task
[2021-12-30 20:59:00,949] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'is_api_avaiable', '2021-12-29T00:00:00+00:00', '--job-id', '60', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp9ykscfon', '--error-file', '/tmp/tmpkjbri75j']
[2021-12-30 20:59:00,949] {standard_task_runner.py:77} INFO - Job 60: Subtask is_api_avaiable
[2021-12-30 20:59:01,098] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.is_api_avaiable 2021-12-29T00:00:00+00:00 [running]> on host airflowvm
[2021-12-30 20:59:01,272] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_avaiable
AIRFLOW_CTX_EXECUTION_DATE=2021-12-29T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-29T00:00:00+00:00
[2021-12-30 20:59:01,272] {http.py:101} INFO - Poking: api/
[2021-12-30 20:59:01,276] {base.py:69} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: None, extra: {}
[2021-12-30 20:59:01,278] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2021-12-30 20:59:11,572] {base.py:243} INFO - Success criteria met. Exiting.
[2021-12-30 20:59:11,579] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_avaiable, execution_date=20211229T000000, start_date=20211230T205900, end_date=20211230T205911
[2021-12-30 20:59:11,633] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-12-30 20:59:11,671] {local_task_job.py:151} INFO - Task exited with return code 0
